SELECT A.OBJECT_NAME, A.PROCEDURE_NAME FROM USER_PROCEDURES A

SELECT PACKAGE_NAME,OBJECT_NAME,ARGUMENT_NAME, A.DATA_TYPE, (A.DATA_LENGTH - A.DATA_SCALE) DATA_LENGTH FROM ALL_ARGUMENTS A WHERE PACKAGE_NAME = 'PG_RELAT';
 
SELECT B.TABLE_NAME, B.COLUMN_NAME, B.DATA_TYPE, (B.DATA_LENGTH - B.DATA_PRECISION) DATA_LENGTH FROM DBA_TAB_COLUMNS B WHERE B.TABLE_NAME LIKE '%VW%';

SELECT A.OBJECT_NAME, A.PROCEDURE_NAME FROM USER_PROCEDURES A WHERE A.OBJECT_NAME = 'PG_RELAT'